default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: urlgen_dev

test:
  <<: *default
  database: urlgen_test

production:
  <<: *default
  database: urlgen_prod