development:
  adapter: postgresql
  database: url_generator
  pool: 5
  timeout: 5000
  username: postgres
test:
  adapter: postgresql
  database: url_generator
  pool: 5
  timeout: 5000
  username: postgres

production:
  adapter: postgresql
  database: url_generator
  pool: 5
  timeout: 5000
  username: postgres